imagePullSecrets: []
package:
  enabled: false
  labels: {}
  annotations: {}
additionalIgnoredNamespaces:
  - 'pepr-system'
  - 'kube-sytem'
  - 'istio-system'
  - 'zarf'
rbac:
  - apiGroups:
      - pepr.dev
    resources:
      - peprstores
    verbs:
      - create
      - get
      - list
      - patch
      - watch
  - apiGroups:
    - ""
    resources:
    - secrets
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - policy.uds.dev
    resources:
      - signatureenforcements
      - sbomenforcements
    verbs:
    - get
    - list
    - watch
  - apiGroups:
      - policy.uds.dev
    resources:
      - signatureenforcements/status
      - sbomenforcements/status
    verbs:
      - patch
      - update
  - apiGroups:
    - apiextensions.k8s.io
    resources:
    - customresourcedefinitions
    verbs:
    - create
    - get
    - patch
    - update
    - list
    - watch
secrets:
  apiPath: 'Yzk0NzE0NGUzMzczODM4OTBlZDc2MzdhM2U0ODEzZmY3YmQ4N2FmYWFkNWJhYWFhYzIzZjAzZmQxNTMzZGMwZg=='
  cosignPublicKey: 'LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFTWZXUFNtMFlhSzZLbkQ2dzhTTXBWemVlVnZrNQpnaVZZY0o2dlFXNWlVTDVlQ1QwN04venAvNHM5Y1IrcjJYdCtCNkRPdFZDcCtyY2NlNTlyczNBdm9nPT0KLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tCg=='
hash: 'd5e451aafbdaeae729d3048137234cb9890572b8a91a30f1c6ce32514085c204'
namespace:
  annotations: {}
  labels:
    pepr.dev: ''
uuid: 'pepr-image-signature-policy'
admission:
  enabled: true
  antiAffinity: false
  terminationGracePeriodSeconds: 5
  failurePolicy: 'Fail'
  env:
    - name: 'PEPR_PRETTY_LOG'
      value: 'false'
    - name: 'LOG_LEVEL'
      value: 'info'
  envFrom: []
  image: 'registry.defenseunicorns.com/navy-canes/controller:v1.2.2'
  annotations:
    pepr.dev/description: 'Pepr policy that enforces cosign image signature verification'
  labels:
    app: 'pepr-image-signature-policy'
    pepr.dev/controller: 'admission'
    pepr.dev/uuid: 'image-signature-policy'
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
    runAsNonRoot: true
    fsGroup: 1000
  readinessProbe:
    httpGet:
      path: '/healthz'
      port: 3000
      scheme: 'HTTPS'
    initialDelaySeconds: 10
  livenessProbe:
    httpGet:
      path: '/healthz'
      port: 3000
      scheme: 'HTTPS'
    initialDelaySeconds: 10
  resources:
    requests:
      memory: '256Mi'
      cpu: '200m'
    limits:
      memory: '512Mi'
      cpu: '500m'
  containerSecurityContext:
    runAsUser: 1000
    runAsGroup: 1000
    runAsNonRoot: true
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - 'ALL'
  podAnnotations: {}
  podLabels: {}
  nodeSelector: {}
  tolerations: []
  extraVolumeMounts:
  - name: cosign-key
    mountPath: /etc/cosign
    readOnly: true
  extraVolumes:
  - name: cosign-key
    secret:
      secretName: cosign-public-key
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchExpressions:
                - key: app
                  operator: In
                  values:
                    - pepr-image-signature-policy
            topologyKey: kubernetes.io/hostname
  serviceMonitor:
    enabled: false
    labels: {}
    annotations: {}
watcher:
  enabled: false
  terminationGracePeriodSeconds: 5
  env:
    - name: 'PEPR_PRETTY_LOG'
      value: 'false'
    - name: 'LOG_LEVEL'
      value: 'info'
  envFrom: []
  image: 'registry.defenseunicorns.com/navy-canes/controller:v1.2.2'
  annotations:
    pepr.dev/description: 'Pepr policy that enforces cosign image signature verification'
  labels:
    app: 'pepr-image-signature-policy-watcher'
    pepr.dev/controller: 'watcher'
    pepr.dev/uuid: 'image-signature-policy'
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
    runAsNonRoot: true
    fsGroup: 1000
  readinessProbe:
    httpGet:
      path: '/healthz'
      port: 3000
      scheme: 'HTTPS'
    initialDelaySeconds: 10
  livenessProbe:
    httpGet:
      path: '/healthz'
      port: 3000
      scheme: 'HTTPS'
    initialDelaySeconds: 10
  resources:
    requests:
      memory: '256Mi'
      cpu: '200m'
    limits:
      memory: '512Mi'
      cpu: '500m'
  containerSecurityContext:
    runAsUser: 1000
    runAsGroup: 1000
    runAsNonRoot: true
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - 'ALL'
  nodeSelector: {}
  tolerations: []
  extraVolumeMounts: []
  extraVolumes: []
  affinity: {}
  podAnnotations: {}
  podLabels: {}
  serviceMonitor:
    enabled: false
    labels: {}
    annotations: {}
