{{- if .Values.admission.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: pepr-image-signature-policy
  namespace: pepr-system
  labels:
    pepr.dev/controller: admission
spec:
  selector:
    app: pepr-image-signature-policy
    pepr.dev/controller: admission
  ports:
  - port: 443
    targetPort: 3000
{{- end }}
    