apiVersion: v1
data:
  value: >-
    NGZmNjVlODY5YTNhYTA3NjQwZGU4NWZjMWI4ZDQ4YzViM2IxNTNiNzUyODJiNTgzMjdkYzcyMjQ4YzI1ZmE5MA==
kind: Secret
metadata:
  name: pepr-image-signature-policy-api-path
  namespace: pepr-system
type: Opaque
