apiVersion: v1
data:
  value: >-
    MTg1ZjMwMDk4ODU1MGRiY2RmNjFiYTkzYmMxMmZhN2ZjNTRlOWJkMzdhMTM5OGI4ZTk4Njc0YjQ5NTI0ZDcxMA==
kind: Secret
metadata:
  name: pepr-image-signature-policy-api-path
  namespace: pepr-system
type: Opaque
