apiVersion: v1
data:
  value: >-
    OWZmNjA1ZWI5ZjZjZGU4ZTdlOGZjOTE5YmQ5OGM3YzkzYmFhMjllMmQzZTk0YmQyYzdmNDBkMzExMzAyYjQxYw==
kind: Secret
metadata:
  name: pepr-image-signature-policy-api-path
  namespace: pepr-system
type: Opaque
