apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ .Values.uuid }}
webhooks:
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      caBundle: >-
        LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tDQpNSUlDdERDQ0FaeWdBd0lCQWdJQkFUQU5CZ2txaGtpRzl3MEJBUXNGQURBY01Sb3dHQVlEVlFRREV4RlFaWEJ5DQpJRVZ3YUdWdFpYSmhiQ0JEUVRBZUZ3MHlOakEwTURjeE1UVTBNRGxhRncweU56QTBNRGN4TVRVME1EbGFNQUF3DQpnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFDWGk3dmZCclQxNytxNFVUbmJFc2wrDQpSVTJxUXdMbzBJaE9KLzRXZ3hLQVhyM3J6Wm9KMU8rcHQydWdSc3ovUmJLOVJDTmNXQ2pNTU5CMzFQWHZ0NkZwDQpURnpmWTNoVWZndStBUWxkK1VVNnZETkpZL2x6Y3FXZXFtMmR4TlMrZkRsQURUSnBpU1JjWTErMjlveGZXQWpvDQpQcGtURitiWWRyZjlrYlBzVkZlVHFzQTlvZWRxMlB2VTNIYzZoTVdyaTdOd213N0VkbGlmd3hnLzNQdGVMYXlhDQpBeWZNWWs1RHpicUJUOXZRcitoNnhyOFVMQW5VUy84azlDSlBhZjZVTFkvam56L3ZrbFNxcFhMYXZQY3c4RkRxDQppelVUS1RjODJHc1UzQlFRNWlScVlzaVZBWTBnV0Fva1lQUGk4VVlFK2RXNXhxQWhNczJ2bFFoY1EyNmpoWE45DQpBZ01CQUFHakhUQWJNQXdHQTFVZEV3UUZNQU1CQWY4d0N3WURWUjBQQkFRREFnTDBNQTBHQ1NxR1NJYjNEUUVCDQpDd1VBQTRJQkFRQUxYQm9abnFrM0pSSi9Fc09mQWVJRmV4dGpoTU9MUExjdE8remR6UGFOMHdsdEE3SXZQNldpDQpMMlJXZ2pWcGRVMyt6a3QwYnZlUWlKYXdZcE1vUVFvZVVxNW1CZm1FU0lvVGk2TGl2Z2JJQjRtakJoamlHd2RxDQpQTGYvdmQ4aFZRcGhxVG0zak1SRXBFWk9CSlB1SUl4WnlFeUQ3YW5LL20yUE9uOGZJeDdoejNpYUR6YXpybDZRDQpXUTV4SnluR1lzbVhiUzh6ajlSZUV4V0tsMUxDczB3VW1sZ0VFYWd4azlCQ3ordTMrSXVxS28zaUdHVTd0M1MwDQpEMCtDcW1vRW1HNG9LQ2huV3d1azBWclM5TWhwaC84RHZwYTd4RXJlT0RrV1ArR3VUTjJmQ0Q0NnZTYmFOVmZJDQpQcG5DMi9jNExOazNmTWVlTnl1SGdjZjdpMlZZcFlDZQ0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQ0K
      service:
        name: {{ .Values.uuid }}
        namespace: pepr-system
        path: >-
          /mutate/185f300988550dbcdf61ba93bc12fa7fc54e9bd37a1398b8e98674b49524d710
    failurePolicy: {{ .Values.admission.failurePolicy }}
    matchPolicy: Equivalent
    name: {{ .Values.uuid }}.pepr.dev
    namespaceSelector:
      matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: NotIn
          values:
            - kube-system
            - pepr-system
            {{- range .Values.additionalIgnoredNamespaces }}
            - {{ . }}
            {{- end }}
            - pepr-system
            - kube-sytem
            - istio-system
            - zarf
    rules:
      - apiGroups:
          - ''
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - pods
          - pods/ephemeralcontainers
    sideEffects: None
    timeoutSeconds: 10
