apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ .Values.uuid }}
webhooks:
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      caBundle: >-
        LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tDQpNSUlDdERDQ0FaeWdBd0lCQWdJQkFUQU5CZ2txaGtpRzl3MEJBUXNGQURBY01Sb3dHQVlEVlFRREV4RlFaWEJ5DQpJRVZ3YUdWdFpYSmhiQ0JEUVRBZUZ3MHlOakEwTWpJeE9UTXdORE5hRncweU56QTBNakl4T1RNd05ETmFNQUF3DQpnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFEUUp5aDVpTXNpS3lxNlBzWC9qdC9DDQo0MCt5Smx6dXRoMU1xdXJpK1REaC9FV1lBNDBTYk81R3N3Z05HRFkyOHk4L2I0UDhxR05va2R2Rjdackw0b080DQp3N1VPVVpENjFIL25vQmNzaVdpZ2JFOWg4dXdNVE1BdlBXRXU3VkpRUEhydHdsSDFFUGJNYThJOEJvejVRMkp5DQp2d1U2Y1hhYkxOYjY1TjVuS3NMSkJGODExcGRQUmlMWTlkbmRoV0srSDVXYm5CbUFxUXFtUHFLZHJLSXNSc0p4DQo2YWpjVlBQdS9TK0t1WEZ5K2VTRVRORjYvZnNVZys0azdSWUVkQVpaaHoreGE1eDd2T1JTSXBlQ1lQaVNFb3l2DQpYVllSVmFwWCtyZ1RqUjl6UG5GWUNTTStIeUluRXNrVWtCN1ZGb3llaWNJWTdTQk1ucFIwbmkwTjExUzNOOFloDQpBZ01CQUFHakhUQWJNQXdHQTFVZEV3UUZNQU1CQWY4d0N3WURWUjBQQkFRREFnTDBNQTBHQ1NxR1NJYjNEUUVCDQpDd1VBQTRJQkFRQjFzN2w3UzBiNVQ3dXFWTWVGOUVsalZUUmhEWVNUSEZvdWdEcDVmcUdiOGVnOW40azk3dXF0DQpwU0hmMGJBWTZSQ2VRT0I2SzZDeC9LYkljVlhlVy9aUGUxbi9Sakg1TTJyMWFpem4xTHVUSzVQaktyRC9pS0VmDQpzMCtPUXRFL1hJU01sSVgvbFVMdGExZFM5VXpHaFVtWUdwcmU0Q3lweVhPMDAwSFZja3lEQWtxTzdlalBDdkFMDQp2Mm9kRTlwcmZTM2ViMit3WStEV21BYUtwYzdPOE43VkxqTjFEZ3h3dms4VTR2T1cwRDFzVk9Zay9pZnNaWThWDQpWYVRNN2Vpek5QdVhHdnV2WFY4ODdBVXVmemt1bFhrbEREeEhKMUdxSHFwL1lBakQxMmtFbXFKMWJuUks5Vkx4DQp1THdwSlJlK0JSQzRYb1EzeG85ZjRRNVA3T3hCZlZVTg0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQ0K
      service:
        name: {{ .Values.uuid }}
        namespace: pepr-system
        path: >-
          /mutate/9ed5afd4838b1dcabf0db9afe9eecb53f353484f402251e3e35c308a6b638bc1
    failurePolicy: {{ .Values.admission.failurePolicy }}
    matchPolicy: Equivalent
    name: {{ .Values.uuid }}.pepr.dev
    namespaceSelector:
      matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: NotIn
          values:
            - kube-system
            - pepr-system
            {{- range .Values.additionalIgnoredNamespaces }}
            - {{ . }}
            {{- end }}
            - pepr-system
            - kube-sytem
            - istio-system
            - zarf
    rules:
      - apiGroups:
          - ''
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - pods
          - pods/ephemeralcontainers
    sideEffects: None
    timeoutSeconds: 10
