apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ .Values.uuid }}
webhooks:
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      caBundle: >-
        LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tDQpNSUlDdERDQ0FaeWdBd0lCQWdJQkFUQU5CZ2txaGtpRzl3MEJBUXNGQURBY01Sb3dHQVlEVlFRREV4RlFaWEJ5DQpJRVZ3YUdWdFpYSmhiQ0JEUVRBZUZ3MHlOakEyTWpNeU1qQTFOVFJhRncweU56QTJNak15TWpBMU5UUmFNQUF3DQpnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFENjRmWnMvM0crRjZoeGg0S1FrUGRWDQpxbEFLS0NJOHBnSnN1S1laVkU3VllRZ3VFckVRSUp1SmlqY3I5OGVIN3hsL2pJL1V5dVYrZ3lDUmM2ZW9Qc0tKDQpkSEVVTkUxYWpJbHc5ZGYzNlBLbnovTXE4T0ZlYWlLM3BSMTMrWnc4b1RHUGJ2blpIbmJTdUVTODA0T1UzRDFTDQpDNnd0MUV4OXBpV1BJTVJOZzVoT0QyQXZOZDh5UFRzQ3dpWGtQMk5jdHVEbVVQZHZ6QTdJNEY5MlZUTE5Bei9BDQpndGVNeVhIbWZ0U1FQZ3hYLy9xWGpaaDNEc3R6MHlRaWQyTlBCSGxhQjJoRTljMDF4VHhpWWlBc3Z3d1ZDZXJ4DQo0VncwU0hQQm4xdDlzeCtmZzBSenJlQ005R2YvT0tlKzNzTTBteW5uTGxSRTczdU9zK2ZCSFFqcDZDSnB6R3BQDQpBZ01CQUFHakhUQWJNQXdHQTFVZEV3UUZNQU1CQWY4d0N3WURWUjBQQkFRREFnTDBNQTBHQ1NxR1NJYjNEUUVCDQpDd1VBQTRJQkFRQ2NIaXdWa3pIZDNGMlA3YTBrYzZXc0dUSENVYmZrem1QeGplOWYyQWZCcndIVTBCdHFJR2xQDQptd2pMemJpaS9aMklocW1OWjdtcU1MMjIrVGM1MXBCZHdWbHdtVE5IMm5WejJEajNqL3ltcSs1K2d0V0N2VGxmDQowVFZIRGtnQU9JR2dKNS9uemRRZ2Z5cDNTUGlGTlMzUUQyV2p5SVNiQndDODFKNVR4VHhEalk2L21HVk04UnFUDQp6OXJTRXlGbjN0R3pXRUZZMjUzeXhLSGM0Y0lzbHJVallQNmhRaDRocU01WWJqckxDcHVZVG10T2JCMTN6aE1VDQo0RWlWOTJrb3RGWjNTM1V6TDNxcHVDVHRCY3Z2QzVzekdHWjFmL2VQUHNPRVhOaUkzeVZROUJJTCtxNnhsN1Y3DQp4ams0QnJrYndqSGs2SFcyN0ZBUzdXakhuWXgrZGRyVQ0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQ0K
      service:
        name: {{ .Values.uuid }}
        namespace: pepr-system
        path: >-
          /validate/c947144e337383890ed7637a3e4813ff7bd87afaad5baaaac23f03fd1533dc0f
    failurePolicy: {{ .Values.admission.failurePolicy }}
    matchPolicy: Equivalent
    name: {{ .Values.uuid }}.pepr.dev
    namespaceSelector:
      matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: NotIn
          values:
            - kube-system
            - pepr-system
            {{- range .Values.additionalIgnoredNamespaces }}
            - {{ . }}
            {{- end }}
            - pepr-system
            - kube-sytem
            - istio-system
            - zarf
    rules:
      - apiGroups:
          - ''
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - pods
          - pods/ephemeralcontainers
      - apiGroups:
          - policy.uds.dev
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
        resources:
          - signatureenforcements
      - apiGroups:
          - policy.uds.dev
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
        resources:
          - sbomenforcements
    sideEffects: None
    timeoutSeconds: 10
