apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ .Values.uuid }}
  {{- if .Values.admission.webhookAnnotations }}
  annotations:
    {{- toYaml .Values.admission.webhookAnnotations | nindent 4 }}
  {{- end }}
  {{- if .Values.admission.webhookLabels }}
  labels:
    {{- toYaml .Values.admission.webhookLabels | nindent 4 }}
  {{- end }}
webhooks:
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      caBundle: >-
        LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tDQpNSUlDdERDQ0FaeWdBd0lCQWdJQkFUQU5CZ2txaGtpRzl3MEJBUXNGQURBY01Sb3dHQVlEVlFRREV4RlFaWEJ5DQpJRVZ3YUdWdFpYSmhiQ0JEUVRBZUZ3MHlOakEzTVRVeE5qVTRNamhhRncweU56QTNNVFV4TmpVNE1qaGFNQUF3DQpnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFDOW1DYkZCR0N6MEljTUZKeG9FMEk4DQpMS1Z3bEdpTlNoVjkraldYNkZud0d3MDV1NlhvcnA4bmthM0NQcDhnR2ZwNVYwdVg0OThlY0hBam1tQ2xJUUdzDQpSMkc0YzBLdTBmeXQzQ2FVNHp5enpNcHMwQTBKU2RvMVRTRG1XbmZsQWZtL3Y4WHBneCtGMFc0K1FVQWZyclVGDQozL0E0SHozcktvK3BIMHAxQ0dFOTJ0YkR5YmFPTEVmbXRSUytUcyt5N05jM1hQLzFreEFkMUhVTkpHbXIwWTdLDQpQT1JxRVNQcmYwcWxCb01pY3ozM2tMdURwN28zYlF4Rmo1a0xGU2loV2tEQmxwVmlGdmNjTWU0RitjYXpYeDBQDQpkOU90bjhQbS9wRU9WRXJ4aU8xN05CaVNqdFVnUjJtaDI4d0lNdDY1b08zbENMQjJNYjFYRWtjV1pCY1BsYUo5DQpBZ01CQUFHakhUQWJNQXdHQTFVZEV3UUZNQU1CQWY4d0N3WURWUjBQQkFRREFnTDBNQTBHQ1NxR1NJYjNEUUVCDQpDd1VBQTRJQkFRQTROYk95U1BnaFFOd2lnVHZEcnM1L0RTQWt5RmppeTRHa2ZwQzVyY210dEJpTjBlTHYrUFYwDQpPU3hJdUZlUDBRbGNORmp4VVRKYzB2cXA1a1lYY1M2SktUOEQ0eVNLcHN4RUxpWGpDSzhuRzZ4U2t1ajFuNUU5DQoxTzZRZFhQbm9NYUVNdzU3ZXY1Y2s5RDFUdEhUMUJqL3VBVCthQnp5ZHFmeG56WkNQVFFIbHc2S3VGMHVJL0RSDQpVS09xZjk5RnZrU1VHeTFZYlkzYWZEeEtrMmE3SG5HMHFOWEZ0YW1QVGYvNmFxMDhsSmlPaFZhbzF1TXNGMEFpDQowdWpIcjRMdmM3anVWSkJQYzQxNHZVNDVvTlQwSmtUMUpLS2RONklTRXBGSzVjd1h2dWFBTXRldVYwWE5NdFMwDQo3ai9mSzk2QXlxb01DM0h1NGVvMEpTNG5uVmlmdjBBVg0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQ0K
      service:
        name: {{ .Values.uuid }}
        namespace: pepr-system
        path: >-
          /validate/9ff605eb9f6cde8e7e8fc919bd98c7c93baa29e2d3e94bd2c7f40d311302b41c
    failurePolicy: {{ .Values.admission.failurePolicy }}
    matchPolicy: Equivalent
    name: {{ .Values.uuid }}.pepr.dev
    namespaceSelector:
      matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: NotIn
          values:
            - kube-system
            - pepr-system
            {{- range .Values.additionalIgnoredNamespaces }}
            - {{ . }}
            {{- end }}
            - pepr-system
            - kube-sytem
            - istio-system
            - zarf
    rules:
      - apiGroups:
          - ''
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - pods
          - pods/ephemeralcontainers
      - apiGroups:
          - policy.uds.dev
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
        resources:
          - signatureenforcements
      - apiGroups:
          - policy.uds.dev
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
        resources:
          - sbomenforcements
    sideEffects: None
    timeoutSeconds: 10
