apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ .Values.uuid }}
webhooks:
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      caBundle: >-
        LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tDQpNSUlDdERDQ0FaeWdBd0lCQWdJQkFUQU5CZ2txaGtpRzl3MEJBUXNGQURBY01Sb3dHQVlEVlFRREV4RlFaWEJ5DQpJRVZ3YUdWdFpYSmhiQ0JEUVRBZUZ3MHlOakExTWpreE5UVTJNVFZhRncweU56QTFNamt4TlRVMk1UVmFNQUF3DQpnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFDdWdJVTZRdzd4bnZ6RWtMZFVIWWZLDQpBcFZGZWJBNDJGSk9WVDI0aXZGTjFoV256d2R5ejV5UCtnSitjN2c4MDB0cGt0UDFNUlJPM0VGMnNHb1FieWxuDQpYdmlVNVd1SUp0ZEVCK3Q4MHRNRG5RdnlXTW9zUXRRSStDZDJmbXJGYnBKK2E4Vm9XcG5YdzBCT204aHR1dkJ0DQowZDRJTGszdmZpbitWTlVWM0tQdWthY3BDTW9PRkxGYnc2eFFMU2JIUEk5OXVqVmdiaEczbzlhRGUrMENoL3M1DQpFV0lLVWNTL0tGNFllbVFDZldGMjdmdytQR2RTTEFDRm9OZUR4NnVJZ3dSb29BOXJKZXFyT0UxZlFtVzFUSG16DQp0RVVSOU1SK2Q5eGhTQVRYd0c4MGxSZ2VpVThTSGdQR245RVl6YjdEeXJJWlUyRTQvRzU2YjRXa0dKZ1F2NHByDQpBZ01CQUFHakhUQWJNQXdHQTFVZEV3UUZNQU1CQWY4d0N3WURWUjBQQkFRREFnTDBNQTBHQ1NxR1NJYjNEUUVCDQpDd1VBQTRJQkFRQ1BYOThEQXlhdVY4azNWZlZJT1FEcWp3TFV1YXZYWnlabk5jbStnaXdwMXNHWjQ3WWx0YlJpDQpJaVZZeWFjK0FjdVI5MFR3UnoxTVZvVFdXNmhqcEdyYW5TQ0ZQR3RzN3dla3B5L0FMU1liRU4rd1ErWVRNMDRVDQpYV2N3RjhWVHNEem9QQzZTOG0xZEpjc2l6Qjl6bFAyMHJvdE04aGJIaDBFOTJ4bDVaOEM4RXVvTUd0bU95c3J6DQpuNTJ5ZVhHUXpzb2lEY3h5TzQrU2ZLODVGNENqMkNtTWhCdFU1aW5UNEE1WW9uQ0tVS01LQUl4TzBiRXI3bEUrDQpDT1RsWktocUh2cGNOVmVtTi9CU2dZZWZrcHg2VDBQYTlyNmNQM1M1UEh0V2xPUGJ1MmdWTSs2TnlOdlpjdm12DQpMS3lrWTFyUkhHTTBqYjFRL2hXTjF0SnoyVXgvYzlrNg0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQ0K
      service:
        name: {{ .Values.uuid }}
        namespace: pepr-system
        path: >-
          /validate/4ff65e869a3aa07640de85fc1b8d48c5b3b153b75282b58327dc72248c25fa90
    failurePolicy: {{ .Values.admission.failurePolicy }}
    matchPolicy: Equivalent
    name: {{ .Values.uuid }}.pepr.dev
    namespaceSelector:
      matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: NotIn
          values:
            - kube-system
            - pepr-system
            {{- range .Values.additionalIgnoredNamespaces }}
            - {{ . }}
            {{- end }}
            - pepr-system
            - kube-sytem
            - istio-system
            - zarf
    rules:
      - apiGroups:
          - ''
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - pods
          - pods/ephemeralcontainers
      - apiGroups:
          - policy.uds.dev
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
        resources:
          - signatureenforcements
      - apiGroups:
          - policy.uds.dev
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
        resources:
          - sbomenforcements
    sideEffects: None
    timeoutSeconds: 10
