kind: ZarfPackageConfig
metadata:
  name: e2e-skip-app
  version: "0.0.1"
variables:
  - name: NAMESPACE
    default: e2e-skip
components:
  - name: skip-app
    required: true
    manifests:
      - name: app
        files:
          - deployment.yaml
    images:
      - docker.io/library/nginx:1.27-alpine
