apiVersion: policy.uds.dev/v1alpha1
kind: SbomEnforcement
metadata:
  name: sbom-dup-first
spec:
  namespaces:
    - e2e-dup
  enforcementPolicy:
    mode: enforce
  deniedComponents:
    - name: anything
      versionRange: "*"
